services:
  - type: web
    name: bizlocate-backend
    env: python
    region: oregon
    plan: free
    buildCommand: cd dragonfly && pip install -r requirements.txt
    startCommand: cd dragonfly && uvicorn unified_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11"
